name: suitmedia_test_mobile_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  gap: ^3.0.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  dartz: ^0.10.1
  infinite_scroll_pagination: ^4.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
